In [2]:
import numpy as np

In [3]:
# checking Numpy version
print()

In [4]:
a = np.array([1,2,3,4,5,6,7,8,9,0])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [5]:
a.dtype

dtype('int32')

In [6]:
a.size

10

In [8]:
a.ndim

1

In [5]:
a.shape

(10,)

In [6]:
a[5]

6

In [7]:
a[::-1]

array([0, 9, 8, 7, 6, 5, 4, 3, 2, 1])

In [8]:
b = np.array([2,4,6,8,0])
b

array([2, 4, 6, 8, 0])

In [9]:
for i, j in zip(a,b):
    c = i + j
c

5

In [10]:
y = np.array([1,2])
z = 2*y
z

array([2, 4])

#### Broadcasting
##### adding constant to a Numpy Array

In [11]:
u = np.array([1,2,3,-1])
z = u + 1   # this adds 1 to each element
z

array([2, 3, 4, 0])

# Plotting Mathematical Function

In [14]:
import matplotlib.pyplot as plt
x = np.linspace(0, 2*np.pi, 100)
y = np.sin(x)
%matplotlib inline
plt.plot(x)